name: reaprime
description: "Streamline Bridge - Gateway for Decent Espresso Machines"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# License
# Copyright (C) 2025-2026 Decent Espresso
# Licensed under GPL v3 - https://www.gnu.org/licenses/gpl-3.0.html

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0
  logging_appenders: ^2.0.0
  flutter_foreground_task: 9.2.0
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shelf: ^1.0.0
  shelf_web_socket: ^3.0.0
  shelf_router: ^1.1.4
  battery_plus: ^7.0.0
  collection: ^1.19.0
  shelf_plus: ^1.11.0
  shadcn_ui: ^0.46.0
  file_picker: ^10.3.8
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  archive: ^4.0.7
  equatable: ^2.0.7
  universal_ble: ^1.1.0
  shared_preferences: ^2.5.3
  # maybe one day? https://github.com/AurelienBallier/flutter_libserialport
  flutter_libserialport:
    # ^0.6.0
    git:
      url: https://github.com/AurelienBallier/flutter_libserialport.git
      ref: main
  # usb_serial: ^0.5.2
  # usb_serial:
  #   git:
  #     url: https://github.com/AurelienBallier/usbserial_dart.git
  #     ref: master
  # usb_serial:
  #   git:
  #     url: https://github.com/jymden/usbserial.git
  #     ref: master
  # flutter_serial_communication: ^0.2.8
  shelf_static: ^1.1.3
  path: ^1.9.1
  shelf_cors_headers: ^0.1.5
  url_launcher: ^6.3.2
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  ansi_escape_codes: ^2.1.0
  flutter_blue_plus: ^2.0.2
  flutter_js:
    # path: ../dart_js
    git:
      url: https://github.com/tadelv/dart_js
      ref: master
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3
  firebase_analytics: ^12.1.0
  http: ^1.2.2
  network_info_plus: ^7.0.0
  window_manager: ^0.5.1
  flutter_inappwebview: ^6.1.5
  device_info_plus: ^12.3.0
  circular_buffer: ^0.12.0
  crypto: ^3.0.3
  # path: ../flutter_libserialport
  # git:
  #   url: https://github.com/tadelv/flutter_libserialport.git
  #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  clock: ^1.1.1
  fake_async: ^1.3.1
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/web/
    - assets/api/
    - assets/plugins/time-to-ready.reaplugin/
    - assets/plugins/visualizer.reaplugin/
    - assets/plugins/settings.reaplugin/
    - assets/defaultProfiles/





