name: reaprime
description: "Reasonable Espresso App"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shelf: ^1.0.0
  shelf_web_socket: ^2.0.1
  shelf_router: ^1.1.4
  battery_plus: ^7.0.0
  collection: ^1.19.0
  shelf_plus: ^1.10.0
  shadcn_ui: ^0.36.1
  file_picker: ^10.1.9
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_archive: ^6.0.3
  equatable: ^2.0.7
  universal_ble: ^0.21.0
  shared_preferences: ^2.5.3
  # maybe one day? https://github.com/AurelienBallier/flutter_libserialport
  flutter_libserialport:
    ^0.6.0
    # git:
    #    url: https://github.com/NeariX67/flutter_libserialport.git
    #    ref: main
  # usb_serial: ^0.5.2
  usb_serial:
    git:
      url: https://github.com/jymden/usbserial.git
      ref: master
  # flutter_serial_communication: ^0.2.8
  shelf_static: ^1.1.3
  path: ^1.9.1
  shelf_cors_headers: ^0.1.5
  url_launcher: ^6.3.2
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  ansi_escape_codes: ^2.1.0
  flutter_blue_plus: ^2.0.2
  flutter_js:
    # path: ../flutter_js
    git:
      url: https://github.com/poviur/dart_js
      ref: master
  # path: ../flutter_libserialport
  # git:
  #   url: https://github.com/tadelv/flutter_libserialport.git
  #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/web/
    - assets/api/
    - assets/plugins/time-to-ready.reaplugin/
    - assets/plugins/visualizer.reaplugin/
